spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/cere-os
          jwk-set-uri: http://localhost:8088/realms/cere-os/protocol/openid-connect/certs
  docker:
    compose:
      lifecycle-management: start_only
